# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d52222c71e5396b66134754c6a67168b4f3a7cd799ff2e5292a59505fa5d8928a2062c4c6c81427f7fc77870e2f83c5e31a2cb787905fa8d6e3200a1305914a

test:
  secret_key_base: d8c2bb7dc41a48b0b5740757f74fc6e0740e249a133dde597564a7e4e2125b67aade425ae921ee0fd5f9711dccffefce3a289456b659141afeb48e670ea242d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
